# -*- coding: utf-8 -*-
"""dag_flightprices

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjooJIyVpYDjf6CxciTDcpntv5pttP2B
"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.dummy import DummyOperator
from airflow.operators.python_operator import PythonOperator
from airflow.providers.postgres.operators.postgres import PostgresOperator


from scripts.flight_prices import load_flight_prices_data

default_args = {
    "retries": 3,
    "retry_delay": timedelta(minutes=1)
}
with DAG(
    dag_id="dag_flightprices",
    start_date=datetime(2023, 11, 28),
    catchup=False,
    schedule_interval="0 * * * *",
    default_args=default_args
) as dag:
    # task con dummy operator
    dummy_start_task = DummyOperator(
        task_id="start"
    )
    load_flight_prices_data_task = PythonOperator(
        task_id="load_flight_prices_data",
        python_callable=load_flight_prices_data,
        op_kwargs={
             "config_file": "/opt/airflow/config/config.ini"
        }
    )
    dummy_end_task = DummyOperator(
        task_id="end"
    )
    dummy_start_task >> load_flight_prices_data_task
    load_flight_prices_data_task >> dummy_end_task

